### PR TITLE
chore: Upgrade swc_ecmascript to 0.36.3

### PR DESCRIPTION
**Pull request by magurotuna**
As title

### CODE REVIEW

**Comment by dsherret** [comment]
@magurotuna do you need a release for this? I think specifying 0.36.3 of swc_ecmascript in deno-lint should work with the existing version.

**Comment by magurotuna** [comment]
Right, release for this is not necessarily required. If you don't think it's needed feel free to close it without merge :)

**Comment by dsherret** [comment]
I will just merge anyway since the tests pass 😀

I'll skip bothering with a release though.

**Comment by magurotuna** [comment]
Alright, thanks!

**Pull request merged**
