### PR TITLE
chore: 0.14.0 - Upgrade swc

### PR DESCRIPTION
**Pull request by magurotuna**
Upgrades swc and bump version to 0.14.0.

### CODE REVIEW

**Review by bartlomieju — APPROVED** [review]
LGTM

**Comment by dsherret** [comment]
Whoops... didn't have the CI running on pull requests for some reason (I've fixed it). `./scripts/setup.sh && ./scripts/generate.sh` needed to be run when changing the swc version so it can output the latest information about the latest swc, then it can generate the new code from that. To make this more straightforward, I've just changed this to a single `./scripts/generate.sh` script and you can provide a `--quick` flag (ex. `./scripts/generate.sh --quick`) to only code generate.

@magurotuna I did a new 0.15.0 release. Please use that one.

**Comment by bartlomieju** [comment]
@dsherret sorry for the trouble 😬

**Comment by dsherret** [comment]
@bartlomieju it was no trouble at all! I managed to fix a few things because of it.... I probably would have missed this as well since the CI didn't build on the PR.

**Comment by magurotuna** [comment]
Thanks for quickly getting it back on the right track!

**Pull request merged**
